<?php /* @var $this \MalibuCommerce\MConnect\Block\Sync\Product */ ?>
<div class="container-fluid">
    <input type="hidden" name="auth" value="<?php echo $this->getAuth() ?>" />
    <input type="hidden" name="identifier" value="<?php echo $this->getIdentifier() ?>" />
    <input type="hidden" name="base_url" value="<?php echo $this->getUrl('') ?>" />

    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->getTitle() ?></h3>
                </div>
                <div class="panel-body">
                    <input type="hidden" name="type" value="product-import" />
                    <div id="console"></div>
                </div>
            </div>
        </div>
    </div>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
