<?php
/**
 * @var $block \MalibuCommerce\MConnect\Block\Navision\OrderHistory
 */
$orders = $block->getOrders();
?>
<form action="<?= $block->getUrl('*/*/orderhistory') ?>" method="post" id="mconnect-orders-list" class="form" autocomplete="off">
    <table>
        <tr>
            <td>
                <fieldset class="fieldset">
                    <div class="field date-from">
                        <label for="date_from"><?= __('Start Date') ?></label>
                        <div class="input-box">
                            <input type="text" id="date_from" name="date_from" title="<?= __('Start Date') ?>" class="input-text" data-validate="{'validate-date':true}" value="<?= $block->getFieldValue('date_from') ?>" style="width: 250px;" />
                            <script type="text/javascript">
                                require([
                                    "jquery",
                                    "mage/mage",
                                    "mage/calendar"
                                ], function ($) {
                                    $("#date_from").calendar({
                                        showsTime: false,
                                        dateFormat: "yy-M-dd",
                                        yearRange: "-120y:c+nn",
                                        buttonText: "Select Date",
                                        changeMonth: true,
                                        changeYear: true,
                                        showOn: "both"
                                    })
                                });
                            </script>
                        </div>
                    </div>
                    <div class="field po_number-from">
                        <label for="po_number_from"><?= __('Start PO Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="po_number_from" name="po_number_from" title="<?= __('Start PO Number') ?>" class="input-text" value="<?= $block->getFieldValue('po_number_from') ?>" />
                        </div>
                    </div>
                    <div class="field order_number-from">
                        <label for="order_number_from"><?= __('Start Order Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="order_number_from" name="order_number_from" title="<?= __('Start Order Number') ?>" class="input-text" value="<?= $block->getFieldValue('order_number_from') ?>" />
                        </div>
                    </div>
                </fieldset>
            </td>
            <td>
                <fieldset class="fieldset">
                    <div class="field date-to">
                        <label for="date_to"><?= __('End Date') ?></label>
                        <div class="input-box">
                            <input type="text" id="date_to" name="date_to" title="<?= __('End Date') ?>" class="input-text" data-validate="{'validate-date':true}" value="<?= $block->getFieldValue('date_to') ?>" style="width: 250px;" />
                            <script type="text/javascript">
                                require([
                                    "jquery",
                                    "mage/mage",
                                    "mage/calendar"
                                ], function ($) {
                                    $("#date_to").calendar({
                                        showsTime: false,
                                        dateFormat: "yy-M-dd",
                                        yearRange: "-120y:c+nn",
                                        buttonText: "Select Date",
                                        changeMonth: true,
                                        changeYear: true,
                                        showOn: "both"
                                    })
                                });
                            </script>
                        </div>
                    </div>
                    <div class="field po_number-to">
                        <label for="po_number_to"><?= __('End PO Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="po_number_to" name="po_number_to" title="<?= __('End PO Number') ?>" class="input-text" value="<?= $block->getFieldValue('po_number_to') ?>" />
                        </div>
                    </div>
                    <div class="field order_number-to">
                        <label for="order_number_to"><?= __('End Order Number') ?></label>
                        <div class="input-box">
                            <input type="text" id="order_number_to" name="order_number_to" title="<?= __('End Order Number') ?>" class="input-text" value="<?= $block->getFieldValue('order_number_to') ?>" />
                        </div>
                    </div>
                </fieldset>
            </td>
        </tr>
    </table>
    <div class="buttons-set">
        <button type="submit" name="search" value="1" title="<?= __('Search') ?>" class="button action submit primary"><span><span><?= __('Search') ?></span></span></button>
    </div>
</form>
<div class="nav-content">
<?php if ($orders && count($orders)): ?>
    <h3><?= __('Orders List') ?></h3>
    <table class="mconnect-nav-table">
        <thead>
        <tr>
            <th><?= __('Order #') ?></th>
            <th><?= __('PO Number') ?></th>
            <th><?= __('Order Date') ?></th>
            <th><?= __('Order Amount') ?></th>
            <th><?= __('Ship To') ?></th>
            <th><?= __('Ship To Address') ?></th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($orders as $order): ?>
            <?php $orderAmount = $block->helper(\Magento\Framework\Pricing\Helper\Data::class)->currency($order->getOrderAmt(), true, false); ?>
            <tr>
                <td><?= $order->getOrderNumber() ?></td>
                <td><?= $order->getPoNumber() ?></td>
                <td><?= date("D, j M, Y", strtotime($order->getOrderDate())) ?></td>
                <td><?= $orderAmount; ?></td>
                <td><?= $order->getShipToName() ?></td>
                <td><?= $order->getShipToAddress() ?></td>
                <td><a target="_blank" href="<?= $block->getUrl('*/*/orderview', ['number' => $order->getOrderNumber()]) ?>"><?= __('View') ?></a></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php elseif ($block->isSearchInitiated()): ?>
    <span><?= __('We couldn\'t find any records.')?></span>
<?php endif?>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#mconnect-orders-list');
        dataForm.mage('validation', {});

    });
</script>
