<form action="<?php echo $block->getUrl('*/*/statementview'); ?>" target="_blank" method="get" id="mconnect-customer-statement-list" class="scaffold-form">
    <table><tr><td>
        <fieldset class="fieldset">
            <div class="field date-from">
                <label for="date_from"><?php echo __('Start Date') ?></label>
                <div class="input-box">
                    <input type="text" id="date_from" name="date_from" title="<?php echo __('Start Date') ?>" class="input-text validate-date required-entry" value="<?php echo $this->getFieldValue('date_from') ?>" style="width: 250px;" />
                    <script type="text/javascript">
                        require([
                            "jquery",
                            "mage/mage",
                            "mage/calendar"
                        ], function ($) {
                            $("#date_from").calendar({
                                showsTime: false,
                                dateFormat: "yy-M-dd",
                                buttonImage: "/pub/static/frontend/Sm/market/en_US/Magento_Theme/calendar.png",
                                yearRange: "-120y:c+nn",
                                buttonText: "Select Date",
                                changeMonth: true,
                                changeYear: true,
                                showOn: "both"
                            })
                        });
                    </script>
                </div>
            </div>
        </fieldset>
    </td>
    <td>
        <fieldset class="fieldset">
            <div class="field date-to">
                <label for="date_to"><?php echo __('End Date') ?></label>
                <div class="input-box">
                    <input type="text" id="date_to" name="date_to" title="<?php echo __('End Date') ?>" class="input-text validate-date required-entry" value="<?php echo $this->getFieldValue('date_to') ?>" style="width: 250px;" />
                    <script type="text/javascript">
                        require([
                            "jquery",
                            "mage/mage",
                            "mage/calendar"
                        ], function ($) {
                            $("#date_to").calendar({
                                showsTime: false,
                                dateFormat: "yy-M-dd",
                                buttonImage: "/pub/static/frontend/Sm/market/en_US/Magento_Theme/calendar.png",
                                yearRange: "-120y:c+nn",
                                buttonText: "Select Date",
                                changeMonth: true,
                                changeYear: true,
                                showOn: "both"
                            })
                        });
                    </script>
                </div>
            </div>
        </fieldset>
    </td></tr></table>
    <div class="buttons-set">
        <button type="submit" name="search" value="1" title="<?php echo __('Search') ?>" class="button"><span><span><?php echo __('Search') ?></span></span></button>
    </div>
</form>
<script>
    var orderListForm = new VarienForm('mconnect-customer-statement-list');
    Calendar.setup({
        inputField: 'date_from',
        ifFormat: '%Y-%m-%d',
        align: 'Bl',
        singleClick: true
    });
    Calendar.setup({
        inputField: 'date_to',
        ifFormat: '%Y-%m-%d',
        align: 'Bl',
        singleClick: true
    });
</script>
