<?php
$_orders = $this->getOrders();
?>
<div class="page-title">
    <h1><?php echo $this->__('Order History') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getUrl('*/*/list') ?>" method="get" id="mconnect-order-list" class="scaffold-form">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="field date-from">
                    <label for="date_from"><?php echo $this->__('Start Date') ?></label>
                    <div class="input-box">
                        <input type="text" id="date_from" name="date_from" title="<?php echo $this->__('Start Date') ?>" class="input-text validate-date" value="<?php echo $this->getFieldValue('date_from') ?>" />
                    </div>
                </div>
                <div class="field date-to">
                    <label for="date_to"><?php echo $this->__('End Date') ?></label>
                    <div class="input-box">
                        <input type="text" id="date_to" name="date_to" title="<?php echo $this->__('End Date') ?>" class="input-text validate-date" value="<?php echo $this->getFieldValue('date_to') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field po_number-from">
                    <label for="po_number_from"><?php echo $this->__('Start PO Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="po_number_from" name="po_number_from" title="<?php echo $this->__('Start PO Number') ?>" class="input-text" value="<?php echo $this->getFieldValue('po_number_from') ?>" />
                    </div>
                </div>
                <div class="field po_number-to">
                    <label for="po_number_to"><?php echo $this->__('End PO Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="po_number_to" name="po_number_to" title="<?php echo $this->__('End PO Number') ?>" class="input-text" value="<?php echo $this->getFieldValue('po_number_to') ?>" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field order_number-from">
                    <label for="order_number_from"><?php echo $this->__('Start Order Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="order_number_from" name="order_number_from" title="<?php echo $this->__('Start Order Number') ?>" class="input-text" value="<?php echo $this->getFieldValue('order_number_from') ?>" />
                    </div>
                </div>
                <div class="field order_number-to">
                    <label for="order_number_to"><?php echo $this->__('End Order Number') ?></label>
                    <div class="input-box">
                        <input type="text" id="order_number_to" name="order_number_to" title="<?php echo $this->__('End Order Number') ?>" class="input-text" value="<?php echo $this->getFieldValue('order_number_to') ?>" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" name="search" value="1" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
    </div>
</form>
<?php if ($_orders && count($_orders)): ?>
<table class="data-table" id="mconnect-orders" >
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('PO Number') ?></th>
            <th><?php echo $this->__('Order Date') ?></th>
            <th><?php echo $this->__('Order Amount') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>
            <th><?php echo $this->__('Ship To Address') ?></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_orders as $_order): ?>
        <tr>
            <td><?php echo $_order->getOrderNumber() ?></td>
            <td><?php echo $_order->getPoNumber() ?></td>
            <td><?php echo date("D, j M, Y", strtotime($_order->getOrderDate())) ?></td>
            <td><?php echo Mage::helper('core')->currency($_order->getOrderAmt(), true, false) ?></td>
            <td><?php echo $_order->getShipToName() ?></td>
            <td><?php echo $_order->getShipToAddress() ?></td>
            <td><a target="_blank" href="<?php echo $this->getUrl('*/*/view', array('number' => $_order->getOrderNumber())) ?>"><?php echo $this->__('View') ?></a></td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif?>
<script>
var orderListForm = new VarienForm('mconnect-order-list');
Calendar.setup({
    inputField: 'date_from',
    ifFormat: '%Y-%m-%d',
    align: 'Bl',
    singleClick: true
});
Calendar.setup({
    inputField: 'date_to',
    ifFormat: '%Y-%m-%d',
    align: 'Bl',
    singleClick: true
});
</script>
