<?php
/**
 * @var \MalibuCommerce\MConnect\Block\Adminhtml\Queue\Log $block
 */

$logDetails = $block->getLogDetails();
?>
<a href="<?php echo $block->getBackUrl() ?>"><?php echo __('Back') ?></a>

<?php foreach($logDetails as $logDetail): ?>
    <?php foreach($logDetail as $title => $contents): ?>
        <hr />
        <h1><?php echo $title ?></h1>
        <?php foreach ($contents as $label => $content): ?>
            <h3><?php echo $label; ?></h3>
            <pre style="white-space: pre-wrap; word-break: break-word; background: #eee;"><code><?php echo htmlspecialchars($content, ENT_XML1); ?></code></pre>
        <?php endforeach; ?>
    <?php endforeach ?>
<?php endforeach ?>
