<?php
/**
 * @var \MalibuCommerce\MConnect\Block\Adminhtml\Queue\Log $block
 */

$logDetails = $block->getLogDetails();
?>
<a href="<?= $block->getBackUrl() ?>"><?= __('Back') ?></a>

<?php foreach ($logDetails as $logDetail): ?>
    <?php foreach ($logDetail as $title => $contents): ?>
        <hr />
        <h1><?= $title ?></h1>
        <?php foreach ($contents as $label => $content): ?>
            <h3><?= $label; ?></h3>
            <pre style="white-space: pre-wrap; word-break: break-word; background: #eee;"><code><?= htmlspecialchars(is_array($content) ? print_r($content, true) : (string)$content, ENT_XML1); ?></code></pre>
        <?php endforeach; ?>
    <?php endforeach ?>
<?php endforeach ?>
