<?php /* @var $block \MalibuCommerce\MConnect\Block\Adminhtml\System\Config\Connection\TriggerPassword */ ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var connectionResult = jQuery('#trigger-password-result');

        jQuery('#trigger_password_button').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    connectionResult.find('.success').hide();
                    connectionResult.find('.failure').hide();
                    connectionResult.find('.processing').show();
                    jQuery('#trigger-password-result-msg').text('');
                    jQuery('#trigger_password_button').prop('disabled', true);
                },
                onSuccess: function(response) {
                    connectionResult.find('.processing').hide();

                    var resultText = '';
                    var json = response.responseJSON;

                    if (response.status > 200) {
                        resultText = response.statusText;
                        connectionResult.find('.failure').show();
                    } else {
                        if (typeof json.success !== 'undefined' && json.success === true) {
                            if (typeof json.p !== 'undefined') {
                                resultText = 'Trigger Password is: ' + json.p;
                            }
                            connectionResult.find('.success').show();
                            jQuery('#trigger_password_button').hide();
                        } else {
                            resultText = 'Failed: please, resave password';
                            connectionResult.find('.failure').show();
                        }
                    }

                    jQuery('#trigger-password-result-msg').text(resultText);
                    jQuery('#trigger_password_button').prop('disabled', false);
                },
                onFailure: function() {
                    connectionResult.find('.success').hide();
                    connectionResult.find('.processing').hide();
                    connectionResult.find('.failure').show();
                    jQuery('#trigger-password-result-msg').text('Internal Error');
                    jQuery('#trigger_password_button').prop('disabled', false);
                }
            });
        });

    });
</script>

<?php echo $block->getButtonHtml() ?>
<span class="connection-indicator" id="trigger-password-result">
    <img class="processing" hidden="hidden" alt="Processing" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="success" hidden="hidden" alt="Success" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <img class="failure" hidden="hidden" alt="Failure" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_remove.gif') ?>"/>
    <span id="trigger-password-result-msg"></span>
</span>