<div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->__('An error was encountered while performing this action') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->__('The error message was:') ?></p>
                <pre><?php echo $this->getException()->getMessage() ?></pre>
                <p><?php echo $this->__('Please check the link you clicked and try again.  If errors persist, contact support.') ?></p>
            </div>
        </div>
    </div>
</div>
