<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?php //echo $this->getTitle() ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php //echo $this->getJsUrl('malibucommerce/mconnect/css/log.css') ?>">
    <link rel="stylesheet" href="<?php //echo $this->getSkinUrl('malibucommerce/mconnect/css/mconnect.css') ?>">
</head>
<body>
<div class="container-fluid">
    <input type="hidden" name="auth" value="<?php //echo $this->getAuth() ?>" />
    <input type="hidden" name="identifier" value="<?php //echo $this->getIdentifier() ?>" />
    <input type="hidden" name="base_url" value="<?php //echo $this->getUrl('') ?>" />
    <?php //echo $this->getChildHtml('mconnect_sync_product') ?>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="<?php //echo $this->getJsUrl('malibucommerce/mconnect/js/vkbeautify.js') ?>"></script>
<script src="<?php //echo $this->getSkinUrl('malibucommerce/mconnect/js/mconnect.js') ?>"></script>
</body>
</html>
