<div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->getTitle() ?></h3>
            </div>
            <div class="panel-body">
                <input type="hidden" name="type" value="product-import" />
                <div id="console"></div>
            </div>
        </div>
    </div>
</div>
